name: lab02

on:
  push:
    paths:
      - "hw/lab02/**"
      - "asm/simpleio_x86_64.S"
      - ".github/workflows/lab02.yml"
  pull_request:
    paths:
      - "hw/lab02/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - "01_i64_to_i32"
          - "02_countdown"
          - "03_mul_shift_add"
          - "04_my_sin"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make python3

      - name: Build
        working-directory: hw/lab02/${{ matrix.task }}
        run: make

      - name: Run tests
        working-directory: hw/lab02/${{ matrix.task }}
        run: make test
